### ISSUE TITLE
test/util.py .tbl.p

### ISSUE THREAD

**Issue by zingdle** [anilshanbhag/crystal#5]
https://github.com/anilshanbhag/crystal/blob/f2179e607eb923f2053a706c1e30aa2b6161b9db/test/util.py#L31

Looks like that `.tbl.p` should be `.tbl`?

**Comment by flfantasy** [comment]
I'm afraid not. The difference between .tbl.p and .tbl is .tbl.p files convert the type of some columns in .tbl files from char(n) to integer. These columns appear in the queries and crystal just processes integer type. Please check [test/ssb/loader/convert.py](https://github.com/anilshanbhag/crystal/blob/master/test/ssb/loader/convert.py) for more details.
