### ISSUE TITLE
Where to run command "make bin/ssl/q11"?

### ISSUE THREAD

**Issue by HennyNile** [anilshanbhag/crystal#7]
Hi, I have a stupid problem. I can not find the bin folder and file q11 after creating a dataset and transfering it when I want to run a query. Where should I run the command "make bin/ssb/q11"?

**Comment by HennyNile** [comment]
Well, I find to make in the first level of crystal and the folder bin is created. However, there is no any file in the folder bin/ssb while I have repeated all steps after running a make in the first level.

**Comment by TKONIY** [comment]
First, before compilation you should download the cub repo by
```
make setup
```
then
```
make make bin/ssb/q11
```

**Comment by HennyNile** [comment]
Oh! It seems to work.
